In [2]:
# -*- coding: utf-8 -*-
"""DS_Day1.ipynb

SyntaxError: incomplete input (3441047287.py, line 2)

In [ ]:
Automatically generated by Colaboratory.

In [ ]:
Original file is located at
    https://colab.research.google.com/drive/1e_nWbF8oWHMcVs0X-zw3IHm3SR2DNPMY
"""

In [ ]:

# 1. **Python Output**
# <br>
print(True)
print("Hello World")
print("Salman Khan")
# print(Salman khan)
print("Bhaio", 123,True, sep = "/")
print("Hello", "World", sep = '-')
print("Hello", end = " ")
print("world")
print("Hello khan")
print(123,True,"Baba", sep = "/", end  =" ")
print("karachi")
#2. Data Types

nteger

In [ ]:
print(8)

e309

In [ ]:
print(1e309)
print(1e123)

ecimal/float

In [ ]:
print(1.76)
print

In [ ]:
print(True)
print(False)

ext/String

In [ ]:
print("Assalam o Alaikum")

complex

In [ ]:
print(5+6j)
print(5+6j)

List -> C -> Array

In [ ]:
print([1,2,3,4,5])

Tuple

In [ ]:
print((1,2,3), end = " ")
print((4,5,6))

Set

In [ ]:
print({1,2,3}, end = " ", sep = "/")
print({4,5,6})

Dictionaries

In [ ]:
print({'Name':'Gulzar', 'Roll No':12})
print({"Name": "Adil", "Roll No": 13})
print({"Name": "Adil", "Roll No": 456})
print({"city": "Karachi",
        "code": 206})

ype

In [ ]:
type([1,2,3])

ariable

In [ ]:
name = "Gulzar"
print(name)

In [ ]:
a  = 5
b = 6
print(a + b)
print(a + b)

Dynamic -> automatically understand what kind of value python variable have

In [ ]:
a = 5
print(type(a))

static <br>
int a = 5

Dynamic binding -> Variables value change as per requirements

In [ ]:
a  = 10
print(a)

In [ ]:
a = 'Gulzar'
print(a)

tatic binding -> The value does not change if any condition<br>
int a = 10

python intelligent

In [ ]:
a = 1
b = 2
c = 12
print(a,b,c)

In [ ]:
a,b,c = 2,4,6
x,y,z = 5,7,8
print(a,b,c)
print(x,y,z)

In [ ]:
a=b=c = 5
a=b=c = 1
print(b)


### Comments<br>

comment

Kayword -> basically predefined word in every language <br>
like : as, if, is, in

Identifiers -> basically we will create it or edit it, and can not starting with digits or special character

In [ ]:
first_name = "Gulzar"
Second_name = "Alam"
print(first_name, Second_name, end = " ")
print(first_name, Second_name)
print(first_name + Second_name, sep = "-")

identifiers can not be keyword

static (remain same) vs Dynamic (real time changes)

In [ ]:
input("Enter your good name ")

Example of dynamic

In [3]:
first_number = input("Enter first number  ")
second_number=input("Enter second number  ")
print(type(first_number), type(second_number))
print(type(first_number), type(second_number))

Enter first number  1
Enter second number  1
<class 'str'> <class 'str'>
<class 'str'> <class 'str'>

add two number

In [4]:
sum = first_number + second_number
print(sum)

11

Type conversion

implicit (interpreter solve itself and find which type of data type ) vs explicit (programmer request to python to change the data type)

example of implicit

In [5]:
print(5 + 5.5)
print(type(5), type(5.5))

10.5
<class 'int'> <class 'float'>

In [6]:
print(5 + "5")

TypeError: unsupported operand type(s) for +: 'int' and 'str'

xplicit has builtin function like: str, int

str -> int

In [ ]:
print("4")

equested to program to change data type

In [ ]:
type(int('4'))
type(str(3))

int -> str

In [ ]:
str(5)

Example<br>
1. take input from users and stored them in variable

In [ ]:
fnum = input("Enter first number: ")
snum = input("Enter second number: ")

add the two number

In [ ]:
sum = int(fnum) + int(snum)
print(sum)
print(type(fnum))

Literals

In [ ]:
a = 0b1010 #Binary literal
print(a)

In [ ]:
b = 100
print(b) #Decimal literals

In [ ]:
c = 0o310 #octal literals
print(c)

In [ ]:
d = 0x12c #Hexa Decimal
print(c)

Operators<br>
1.Arithmetic<br>
2. Logical <br>
3. Assignment<br>
4. Bitwise<br>
5. Relational<br>
6. Membership

loat literals

In [7]:
float_1 = 1.5
float_2 = 1.5e2 #1.5 x 10^2
float_3 = 1.5e-2

In [8]:
print(float_1, float_2, float_3)

1.5 150.0 0.015

omplex literals

In [10]:
a = 3.14j
b = 3.14j
print(b.real, b.imag)
print(a.real, a.imag)

0.0 3.14
0.0 3.14

Python String

In [11]:
string = 'This is python'
strings = "This is python"
char = 'C'
unicode = u"\U0001f600"
raw_data=r"raw \n string"

In [12]:
print(string)
print(strings)
print(char)
print(unicode)
print(raw_data)

This is python
This is python
C
😀
raw \n string

In [13]:
a = True + 1
b = False - 1

In [14]:
print("a:" , a)
print("b:" ,  b)

a: 2
b: -1

In [15]:
a = None
print(a )

None